#pragma config(Motor,  motorA,          draw,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[draw]=15;
	wait1Msec(2000);
	motor[draw]=0;
}
