#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Sensor, S2,     touch,          sensorEV3_Touch)
#pragma config(Motor,  motorA,          draw,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool run=false;
int power=1;


task main()
{
	nMotorEncoder[motorA]=0;
while(true){
	int encoder=nMotorEncoder[motorA];
	displayCenteredBigTextLine(4, "Right: %d", encoder);
	if(SensorValue[sound]>70){
		if(run){
			run=false;
	}else{
		run=true;
	}
}
if(encoder<360*5&&encoder>-360*5){
	if(run){
		motor[draw]=15*power;
	}else{
		motor[draw]=0;
	}
}else{
	motor[draw]=0;
}

if(SensorValue[touch]==0){
	power=-1;
}else{
	power=1;
}
}
}
