#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Sensor, S2,     touch,          sensorEV3_Touch)
#pragma config(Motor,  motorA,          draw,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main(){
while(true){
	nMotorEncoder[motorA]=0;
	while(true){
	displayCenteredBigTextLine(4, "Right: %d", nMotorEncoder[motorA]);
	motor[draw]=15;
}
	}
}
